---
- name: Deploy VMware Virtual Machine
  hosts: localhost #10.112.31.182
  become: true
  gather_facts: no
  vars:
    # VM resource definition
    vm_name: "test-backend-vm"
    memory: 4096
    cpus: 3
    
    # Cloud-init Parameters (user/meta data)
    ssh_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDtcQjezv09vEgG9jvHPZyEGipgeP+hNxnj4lJ0hClvh5dQzJmfBdLBpUDQ6ChRSOYvo+Hk2hljeonpqrV+/0lO8R0/XHR/0cKWUCD2T3isPhph+NGw15/XsVCzhHqLUvnDJh7pv6Uc16a3mKmOf/DG7ct+0vMZCMNKmqD0Wmkls8tj/C+OT0c01T3e2bXgUhBmq9g6Hefm78/IqRQbABwwDu+JMwadhBWXLsWJWHDvHWKxO+J5vRSVn76+ZThm+srRjNtLolpz03lhQGdf5tGJK/VH1WH2loxzkeFH5wddb+Fg1gzV4mRonkY/p5lAhas6EU7ZnxVxaKDjyfcLoqu9vdZhjR7FhyXISBDd03zQ4W9yQj7hM9QIM4oJc1bNGqKY0uvWW2DeZmvBsU4DK6BICH6jCcg0ajEOyCetrxpwBg5KiSN8H3EK49VYYzqTZR0I1dy6gkbo3jAOx+G4V5+AsJDVSjkdgBDAZAf16HkQjrsce79n4W5+t3fSdp9X9hU= ahmedtb@otbs-LTP641.onetech-group.corp"
    instance_ip: "10.112.41.151/24"
    ipv4_gateway: "10.112.41.254"
    host_name: "test-backend-vm.onetech-group.corp"
    domain: "onetech-group.corp"
    dns: "10.112.100.100"
    
    # Cloud-init Userdata
    user_name: "Ahdy"
    password: "$6$rounds=4096$5SvNFgkUdsGmXZN.$8v2lKGZ.h1n06uNsAEZTpvENWmV1gzywVD4tZpgaWXb5X3tdwZKLJ7/vpLUxRV/RezK.RGFW74PwVI1P2fshw0"
    
    # Additional disks
    additional_disks: []
    
    # Resource ID
    resource_id: "test7b4436e4"

  tasks:
    - name: Gather input variable values
      ansible.builtin.template:
        src: terraform.tfvars.j2
        dest: /home/ahmedtb/Cumulus/linux-vmware-vm/terraform/terraform.tfvars
     
    - name: Prepare workspace environment
      command: "terraform workspace new {{ resource_id }}"
      args:
        chdir: /home/ahmedtb/Cumulus/linux-vmware-vm/terraform
        
    # - name: Switch to the created workspace
    #   command: "terraform workspace select {{ resource_id }}"
    #   args:
    #     chdir: /home/ahmedtb/Cumulus/linux-vmware-vm/terraform
        
    - name: Linux Virtual machine creation with full customization
      ansible.builtin.terraform:
        project_path: /home/ahmedtb/Cumulus/linux-vmware-vm/terraform
        force_init: true
        complex_vars: true  # This will override terraform to accept the variables of type dictionaries, lists, and booleans
        workspace: "{{resource_id}}"